### PR TITLE
Wiki audit

### PR DESCRIPTION
**Pull request by lucascolley**
Here's my audit of the wiki, let me know what you think!

## Active (keep)

- [1.13.0 release notes](https://github.com/scipy/scipy/wiki/*Release-Note-Entries-for-SciPy-1.13.0-(asterisk-makes-this-appear-at-the-top))
- [CI dev best practices](https://github.com/scipy/scipy/wiki/Best-practice-for-development-of-CI-configurations)
- [SciPy 2.0 ideas](https://github.com/scipy/scipy/wiki/Ideas-for-changes-&-cleanups-in-SciPy-2.0)

## Unsure?

- [`scipy.signal` to-do list](https://github.com/scipy/scipy/wiki/scipy.signal-to-do-list) - clearly out of date but perhaps relevant stuff there?
- [Web service infrastructure](https://github.com/scipy/scipy/wiki/Web-service-infrastructure) - this should be replaced with up to date information, either on the wiki or elsewhere
- [Cython wrappers](https://github.com/scipy/scipy/wiki/Cython-Wrappers) - probably a bit out of date but still valuable info
- [Dropping support for accelerate](https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate) - archive now that we are bringing accelerate back?
- [Reading `mat` files](https://github.com/scipy/scipy/wiki/Reading-mat-file-class-objects) - keep if still relevant?

## Archive (no longer relevant but historically valuable) - in this PR

- GSoC Project Ideas 2015-2019, 2021-2022
- GSoC 2014 Discrete Wavelet Transforms
- GSoC Rotation Formalism
- GSoD 2022
- GSoC `scipy.diff`
- SciPy development hangouts

## Delete (no longer relevant and no historical value)

- [Windows 10 build demo](https://github.com/scipy/scipy/wiki/Easy-Windows-10-Build-Scipy-from-source) - outdated (or archive?)
- [THANKS.txt 1.5.0](https://github.com/scipy/scipy/wiki/THANKS.txt-additions-modifications-for-1.5.0*)
- [THANKS.txt 1.6.0](https://github.com/scipy/scipy/wiki/THANKS.txt-additions-modifications-for-1.6.0*)
- [1.10.0 release notes](https://github.com/scipy/scipy/wiki/Release-Note-Entries-for-SciPy-1.10.0)
- [1.11.0 release notes](https://github.com/scipy/scipy/wiki/Release-Note-Entries-for-SciPy-1.11.0)
- [1.9.0 release notes](https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.9.0)
- [1.8.0 release notes](https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.8.0)
- [1.7.0 release notes](https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.7.0)
- [GSoD 2019](https://github.com/scipy/scipy/wiki/Google-Summer-of-Docs-2019)

---

We can then point to this archive from the wiki home page.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks Lucas!

- all the ones under delete can indeed go, including the Windows 10 build demo page,
- the Active ones indeed look fine to keep,
- agreed with the Archive ones too
- for the Unsure ones:

  - `scipy.signal`: perhaps leave that one where it is. There's some cleanup in progress and some months left to run on work on `cupyx.scipy.signal`; once that ends it may be good to update the page or decide what is still relevant (@ev-br will know better than me)
  - web service infra: a bit outdated, but still some useful info. I suggest to leave it alone for now,
  - notes on Cython: doesn't quite belong on the wiki. some useful info there perhaps, so needs considering whether anything is useful to move to the Cython docs or elsewhere,
  - Dropping support for Accelerate: that page is linked to in multiple places. It's fine to archive now, but let's leave at least a stub around pointing to the archive location,
  - Reading `.mat` files: I suggest to copy the contents into a regular issue, saying that it's from this wiki page and was last edited in 2015. Then close the issue straight away. That's more discoverable than archiving and potentially useful.

**Comment by ev-br** [comment]
Re: signal todo list, some parts of it were done in the meantime, but not all. So probably best to move it at least parts of it to an issue or several. WDYT @endolith?

**Comment by lucascolley** [comment]
> all the ones under delete can indeed go, including the Windows 10 build demo page

Deleted now 👍

> notes on Cython: doesn't quite belong on the wiki. some useful info there perhaps, so needs considering whether anything is useful to move to the Cython docs or elsewhere

I opened https://github.com/cython/cython/issues/6059.

> Dropping support for Accelerate: that page is linked to in multiple places. It's fine to archive now, but let's leave at least a stub around pointing to the archive location

Added to this PR.

> Reading .mat files: I suggest to copy the contents into a regular issue, saying that it's from this wiki page and was last edited in 2015. Then close the issue straight away. That's more discoverable than archiving and potentially useful.

Done https://github.com/scipy/scipy/issues/20192.

**Comment by rgommers** [comment]
Thanks Lucas!

**Comment by endolith** [comment]
> Re: signal todo list, some parts of it were done in the meantime, but not all. So probably best to move it at least parts of it to an issue or several. WDYT @endolith?

I don't know.  Some of them have issues already but it's nice to see them in one place.  But maybe that could be achieved through issue tags or something?  I haven't had time to contribute to scipy in a while...

**Comment by ev-br** [comment]
> I haven't had time to contribute to scipy in a while...

You are missed! Life goes on its own pace as always. Happy to see you back and hope you'll have time in some foreseeable future!

**Pull request merged**
